### PR TITLE
Migrate package to ROS 2.

### PR DESCRIPTION
**Pull request by luator**
## Description

Migrate to ROS 2

## How I Tested

Built the BLMC_EI project and ran a few demos.

### CODE REVIEW

**Review by MaximilienNaveau — COMMENTED** [review]
I organised these kind of package using a pure python package see:
https://github.com/open-dynamic-robot-initiative/robot_properties_solo/

**Comment by luator** [comment]
Is there a benefit in using Python instead of CMake?  There is no python code in this package after all.

**Comment by MaximilienNaveau** [comment]
No there is not just a kind of uniformity in the packaging. but I do not have strong opinion you should merge this and we may talk later about what to do.

**Comment by luator** [comment]
I actually found a benefit of using Python. If it can also be installed without colcon in this case, we could use it in a pure-python installation of our simulation (i.e. without colcon).  We currently support this by keeping copies of the URDF files in the simulation package which I would be very happy to get rid of.

I would prefer to do this at a later PR, though, to not delay the migration.

**Comment by MaximilienNaveau** [comment]
ok

**Pull request merged**
